# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-08-09 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdog',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
