# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-08-07 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_filename', models.ImageField(blank=True, null=True, upload_to='dogs')),
                ('breed', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=1)),
                ('size', models.CharField(max_length=2)),
            ],
        ),
    ]
